# Generated by Django 4.0 on 2022-01-14 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='app_MakePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=100)),
                ('userEmail', models.CharField(max_length=100)),
                ('userPhone', models.CharField(max_length=100)),
                ('userAddress', models.CharField(max_length=100)),
                ('userAmount', models.IntegerField()),
            ],
        ),
    ]
