# Generated by Django 4.0 on 2022-01-06 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='m_slug',
            field=models.SlugField(blank=True, max_length=1000, null=True),
        ),
    ]
