# Generated by Django 3.1.7 on 2022-01-12 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_viewProduct', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='m_OfferStatus',
            field=models.CharField(default='inactive', max_length=30),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='m_eidDiscount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='m_regularDiscount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='m_studentDiscount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
