# Generated by Django 4.0 on 2022-01-30 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_viewProduct', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
            ],
        ),
    ]
