# Generated by Django 4.0 on 2022-01-30 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_viewProduct', '0004_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
