# Generated by Django 3.2.10 on 2022-01-13 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='email',
            new_name='m_email',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='message',
            new_name='m_message',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='name',
            new_name='m_name',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='subject',
            new_name='m_subject',
        ),
    ]
