# Generated by Django 3.2.10 on 2022-01-13 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0003_message_room'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
