# Generated by Django 4.0 on 2022-01-14 07:29

from django.db import migrations
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blogmodel_m_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='m_content',
            field=froala_editor.fields.FroalaField(),
        ),
    ]
