# Generated by Django 4.0 on 2022-01-31 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProposedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productCaption', models.CharField(max_length=100)),
                ('productPrice', models.CharField(max_length=100)),
                ('productImage', models.ImageField(upload_to='img/%y')),
            ],
        ),
    ]
