# Generated by Django 3.1.7 on 2022-01-07 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_comment', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UnlikeModel',
        ),
    ]
