# Generated by Django 3.1.7 on 2022-01-07 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_comment', '0003_auto_20220107_1549'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserLikeModel',
        ),
    ]
