# Generated by Django 3.1.7 on 2022-01-07 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_comment', '0004_delete_userlikemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentmodel',
            name='m_like',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='commentmodel',
            name='m_unlike',
            field=models.IntegerField(default=0),
        ),
    ]
