# Generated by Django 3.1.7 on 2022-01-07 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_comment', '0005_auto_20220107_1625'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentmodel',
            name='m_like',
        ),
        migrations.RemoveField(
            model_name='commentmodel',
            name='m_unlike',
        ),
    ]
