# Generated by Django 3.1.7 on 2022-01-08 02:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_comment', '0006_auto_20220107_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentmodel',
            name='m_comment_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
