# Generated by Django 3.1.7 on 2022-01-08 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_comment', '0007_auto_20220108_0813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentmodel',
            name='m_comment_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
