# Generated by Django 3.1.7 on 2022-01-08 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_comment', '0008_auto_20220108_0841'),
    ]

    operations = [
        migrations.AddField(
            model_name='replymodel',
            name='m_reply_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
