# Generated by Django 4.0 on 2022-01-06 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UiImage',
        ),
    ]
