# Generated by Django 4.0 on 2022-01-09 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageShowModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_imageShowName', models.CharField(max_length=100)),
                ('m_imageShowimage', models.ImageField(upload_to='UiImage/')),
            ],
        ),
        migrations.DeleteModel(
            name='UiImage',
        ),
    ]
