# Generated by Django 4.0 on 2022-01-14 04:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='BkashTransaction',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('paymentID', models.CharField(max_length=50)),
                ('createTime', models.TextField()),
                ('updateTime', models.TextField()),
                ('trxID', models.CharField(editable=False, max_length=50, primary_key=True, serialize=False, unique=True)),
                ('transactionStatus', models.CharField(max_length=20)),
                ('amount', models.CharField(max_length=20)),
                ('currency', models.CharField(max_length=20)),
                ('intent', models.CharField(max_length=20)),
                ('merchantInvoiceNumber', models.CharField(max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bkashtransactions', to='auth.user')),
            ],
            options={
                'db_table': 'bkashtransactions',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='BkashPayment',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('paymentID', models.CharField(editable=False, max_length=50, primary_key=True, serialize=False, unique=True)),
                ('createTime', models.TextField()),
                ('orgLogo', models.URLField(max_length=250)),
                ('orgName', models.CharField(max_length=100)),
                ('transactionStatus', models.CharField(max_length=50)),
                ('amount', models.CharField(max_length=50)),
                ('currency', models.CharField(max_length=20)),
                ('intent', models.CharField(max_length=20)),
                ('merchantInvoiceNumber', models.CharField(max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bkashpayments', to='auth.user')),
            ],
            options={
                'db_table': 'bkashpayments',
                'ordering': ('-created',),
            },
        ),
    ]
