# Generated by Django 4.0 on 2022-01-06 11:51

from django.db import migrations, models
import froala_editor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_title', models.CharField(max_length=1000)),
                ('m_content', froala_editor.fields.FroalaField()),
                ('m_slug', models.SlugField(max_length=1000)),
                ('m_image', models.ImageField(upload_to='blog')),
                ('m_createdAt', models.DateTimeField(auto_now_add=True)),
                ('m_uploadTo', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
