# Generated by Django 4.0 on 2022-01-07 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blogmodel_m_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='m_content',
            field=models.TextField(),
        ),
    ]
