# Generated by Django 4.0 on 2022-01-07 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_image', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='price',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
    ]
